name: MCWipeout
version: 1.0
authors: [Aylias, Seailz, Sloimay]
main: main.java.live.wipeout.chatchannels.Main
api-version: 1.17
commands:
  wipeout:
    usage: /wipeout player
  mcw_teams:
    usage: /mcw_teams